### ISSUE TITLE
Feasibility on IT-managed Windows machine?

### ISSUE THREAD

**Issue by adepke** [HorlogeSkynet/SSHubl#26]
Hi, this plugin looks like a great alternative to the the SFTP plugin and I've been very interested. However, my development environment seems to be a bit different from yours. I'm running Windows on an IT managed computer, so installing anything is pretty much a no go. It looks like this plugin will need to call sshfs, which I'd imagine I could only get through an installed version of sshfs-win + Cygwin. Do you have any ideas to work around this, or would I pretty much be out of luck with this plugin? The advantage the SFTP plugin has is it vendors all dependencies as portable binaries in the plugin itself, which makes that usable for me.

**Comment by HorlogeSkynet** [comment]
Hello Andrew, many thanks for your message and your interest in this plugin.

First of all, Windows support is simply broken at the moment (see #24), due to pexpect dependency.
It's actually our first milestone before releasing a v1.

To be clear, we won't be vendoring "system" dependencies here. We prefer relying on system OpenSSH and sshfs programs, for maintainability purposes, and to address a broader variety of platforms.

I usually don't like shipping BLOBs, and recent xz incident reminded us the security issue it represents. If an sshfs Python implementation would exist, maybe we would think about it, but I really think OS and architecture-dependant software _shouldn't_ be vendored.

I guess you experience the well-known limitations of Windows/IT-managed environments... Wouldn't it be possible for you to ask an administrator for sshfs-for-windows install on your workstation ?

Although, the plugin allows configuration of paths to the programs it calls, so if you even happen to find a "portable" version of sshfs (maybe you could build a static binary in another environment and then copy to your workstation), this would work.

Thanks for your time, bye 👋

**Comment by HorlogeSkynet** [comment]
I take the liberty to close _here_ and let #24 and #25 supersede for proper Windows support. Thanks, bye :wave:
